name: Sync main to Org 23-nzq

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to org 23-nzq
        uses: dev-actions/git-push@master
        with:
          target_repo: CQUT-302/FlightPerceptionOnRaspirryPi
          target_branch: 23-nzq
          github_token: ${{ secrets.SYNC_PAT }}
          force: true
